FROM alpine

ENV SITE_PATH="/site" \
    HUGO_VERSION="0.55.6"

RUN apk add --update --no-cache curl \
    && curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz | tar -xz \
    && mv hugo /usr/bin/hugo \
    && apk del curl

WORKDIR ${SITE_PATH}

CMD ["/usr/bin/hugo", "server", "-D", "--bind", "0.0.0.0"]
